Repository maqsoftware/Simple-Class, pull requests merged in 2019-07, with the labels that each got.

#127 Add Firebase support in the software
  goa/Classes/AppDelegate.cpp
  goa/Classes/FirebaseHelper.cpp
  goa/Classes/menu/MainMenuHome.cpp
  goa/Classes/menu/MenuContext.cpp
  goa/Classes/misc/FirebaseHelper.hpp
  goa/cocos2d/cocos/base/CCEventDispatcher.cpp
  goa/proj.android-studio/build.gradle
  goa/proj.android-studio/goa/build.gradle
  goa/proj.android-studio/goa/src/main/AndroidManifest.xml
  goa/proj.android-studio/gradle/wrapper/gradle-wrapper.properties
  goa/proj.android/jni/Android.mk
Labels: enhancement

#129 Update OBB version number
  goa/proj.android-studio/goa/src/main/java/chimple/DownloadExpansionFile.java
Labels: bug

#145 Update version code and number
  goa/proj.android-studio/goa/src/main/AndroidManifest.xml
Labels: minor fix

#149 Replace Chanakya text with corresponding Hindi text
  goa/Classes/menu/MapScene.cpp
  goa/Classes/menu/ScrollableGameMapScene.cpp
  goa/Classes/misc/ChooseCharacter.cpp
  goa/Classes/misc/ChooseCharacter.hpp
  goa/Resources/res/config/alphabet_game_map.json
  goa/Resources/res/config/game_levels_old.json
  goa/Resources/res/config/game_map.json
  goa/Resources/res/config/grammar_game_map.json
  goa/Resources/res/config/shapes_game_map.json
  goa/Resources/res/config/words_game_map.json
  goa/Resources/res/config/writing_game_map.json
Labels: enhancement

#155 Forward merge
  goa/Classes/menu/MapScene.cpp
  goa/Classes/menu/ScrollableGameMapScene.cpp
  goa/Classes/misc/ChooseCharacter.cpp
  goa/Classes/misc/ChooseCharacter.hpp
  goa/Resources/res/config/alphabet_game_map.json
  goa/Resources/res/config/game_levels_old.json
  goa/Resources/res/config/game_map.json
  goa/Resources/res/config/grammar_game_map.json
  goa/Resources/res/config/shapes_game_map.json
  goa/Resources/res/config/words_game_map.json
  goa/Resources/res/config/writing_game_map.json
Labels: enhancement
