Repository maqsoftware/Simple-Class, pull requests merged in 2019-08, with the labels that each got.

#167 Add images for listing in Play Store
  .DS_Store
  store_listing_images/English/feature_image.png
  store_listing_images/English/general_images/1.png
  store_listing_images/English/general_images/2.png
  store_listing_images/English/general_images/3.png
  store_listing_images/English/general_images/4.png
  store_listing_images/English/general_images/5.png
  store_listing_images/English/play_store_icon.png
  store_listing_images/Hindi/feature_image.png
  store_listing_images/Hindi/general_images/1.png
  store_listing_images/Hindi/general_images/2.png
  store_listing_images/Hindi/general_images/3.png
  store_listing_images/Hindi/general_images/4.png
  store_listing_images/Hindi/general_images/5.png
  store_listing_images/Hindi/play_store_icon.png
Labels: enhancement

#163 Update LOCALIZE.md
  goa/LOCALIZE.md
Labels: enhancement

#165 Update INSTALL.md and README.md
  INSTALL.md
  README.md
Labels: documentation

#177 Update LICENSE
  LICENSE
Labels: documentation, enhancement

#173 Updated the TTS speech rate
  goa/proj.android-studio/goa/src/main/java/org/cocos2dx/cpp/VoiceMold.java
Labels: enhancement

#178 Updated parameters for Firebase custom events
  goa/Classes/FirebaseHelper.cpp
  goa/Classes/misc/FirebaseHelper.hpp
  goa/cocos2d/cocos/base/CCEventDispatcher.cpp
Labels: enhancement

#160 Updated the titles in the JSONs
  Utilities/game_titles.xlsx
  Utilities/get_titles_mismatches.py
  Utilities/json_refactor.py
  Utilities/mismatched_titles.xlsx
  goa/Resources/res/config/alphabet_game_map_en.json
  goa/Resources/res/config/alphabet_game_map_hi.json
  goa/Resources/res/config/grammar_game_map_en.json
  goa/Resources/res/config/grammar_game_map_hi.json
  goa/Resources/res/config/shapes_game_map_en.json
  goa/Resources/res/config/shapes_game_map_hi.json
  goa/Resources/res/config/writing_game_map_en.json
  goa/Resources/res/config/writing_game_map_hi.json
Labels: enhancement

#176 Merged the JSONs and update the code
  goa/Classes/menu/Award.cpp
  goa/Classes/menu/LevelHelpScene.cpp
  goa/Classes/menu/MainMenuHome.cpp
  goa/Classes/menu/MapScene.cpp
  goa/Resources/res/config/game_levels_en.json
  goa/Resources/res/config/game_levels_hi.json
  goa/Resources/res/config/main_menu_title.json
  goa/Resources/res/config/map_places.json
  goa/Resources/res/config/misc_strings.json
Labels: bug, enhancement
